---
- name: Make sure nginx is enabled & running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy nginx config file
  copy:
    src: nginx-config-default
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

